### ISSUE TITLE
Error loading Solution ChartWin.Sln

### ISSUE THREAD

**Issue by paul1956** [AngeloCresta/winforms-datavisualization-net5#1]
\Source\Repos\winforms-datavisualization-net5\src\System.Windows.Forms.DataVisualization.Design\System.Windows.Forms.DataVisualization.Design.csproj : error  : The project file cannot be found.

that file does not exist in fact the system directory does not exist.

BTW the demos look great and run.

**Comment by AngeloCresta** [comment]
It's strange, I've right now downloaded the zip file of the project and everything was ok, can you try again?
the Design project is not part of the solution, you have to open the "DataViz.sln" in the main directory not the "ChartWin.sln".
I'll remove the file to avoid misunderstandings

Regards,
Angelo

**Comment by paul1956** [comment]
I didn't use the zip, I opened using Clone from Visual Studio, I just wanted to build the Nuget and use the library. I am unfamiliar with how to just include the library in my project any info would be helpful.
