### ISSUE TITLE
How do I set the color of the background outside the border?

### ISSUE THREAD

**Issue by paul1956** [AngeloCresta/winforms-datavisualization-net5#2]
The chart is sitting on a Black TabPage, but the area outside the border is always white.
![image](https://user-images.githubusercontent.com/12789369/119214736-df011300-ba7d-11eb-93c8-42556263b730.png)

**Comment by AngeloCresta** [comment]
try to comment out a line like this in the .designer.cs file:

`
this.chart1.BorderSkin.SkinStyle = System.Windows.Forms.DataVisualization.Charting.BorderSkinStyle.Emboss;
`
-->
`
//this.chart1.BorderSkin.SkinStyle = System.Windows.Forms.DataVisualization.Charting.BorderSkinStyle.Emboss;
`

**Comment by paul1956** [comment]
Thanks
