### ISSUE TITLE
Would you accept PR to clean up code are remove all the messages

### ISSUE THREAD

**Issue by paul1956** [AngeloCresta/winforms-datavisualization-net5#3]
Either with suppressions or some code changes? Feel free to close if not.

**Comment by SuperDaveOsbourne** [comment]
I have already updated it to .Net 6 with VS 2019 16.11.0 preview 1 and done all the recommended refactoring's if your interested. About 1000 changes. So far all the examples work. Going after it today with  ReSharper tonight. Let me know if anyone is interested since I did all that work already.

**Comment by paul1956** [comment]
Yes I did it to, but I will take yours. ReSharper is currently not working on my machine. I will close.
